services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=realestate
      - POSTGRES_USER=mkon_user
      - POSTGRES_PASSWORD=secure_db_pass
    networks:
      - internal

  web:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://mkon_user:secure_db_pass@db:5432/realestate
      - DEBUG=False
      - ALLOWED_HOSTS=realestate.mkon.tech
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    networks:
      - traefik-public
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.arthi-secure.rule=Host(`arthiproperties.mkon.tech`)"
      - "traefik.http.routers.arthi-secure.entrypoints=websecure"
      - "traefik.http.routers.arthi-secure.tls.certresolver=myresolver"
      - "traefik.http.services.arthi-svc.loadbalancer.server.port=8000"

      - "traefik.http.routers.arthi-media.rule=Host(`arthiproperties.mkon.tech`) && PathPrefix(`/media/`)"
      - "traefik.http.routers.arthi-media.entrypoints=websecure"
      - "traefik.http.routers.arthi-media.tls.certresolver=myresolver"

networks:
  traefik-public:
    external: true
  internal:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
