# Generated by Django 6.0.1 on 2026-01-23 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_agent'),
        ('listings', '0003_property_has_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.agent'),
        ),
    ]
